### ISSUE TITLE
What's the license of contents hosted on this repo and the site?

### ISSUE THREAD

**Issue by tisonkun** [Nutlope/whatisdevrel#14]
Hi @Nutlope,

I like this site and its valuable content, and I may want to refer part of them in my blogs or presentations (that is, share and adapt).

Since I don't find a license of contents hosted here, I create this issue for advices.

Thank you for such a wonderful webpage :)

**Comment by Nutlope** [comment]
Hi @tisonkun! Thank you for checking. We don't have a license yet so feel free to reuse any content as long as you mention that it came from the site.

**Comment by tisonkun** [comment]
https://mp.weixin.qq.com/s/AigRVAOpFCGh4_nUTcDsJQ

FYI here's a Chinese post referring to What is DevRel site :)
